name: "Trigger and Wait for Workflows"
description: "Triggers one or more workflows in a different repository and waits for them to end"
inputs:
  github_token:
    description: "GitHub token"
    required: true
  repo:
    description: "Repository to trigger workflows in (format: owner/repo)"
    required: false
  workflow_id:
    description: "ID or filename of the workflow to trigger"
    required: false
  ref:
    description: "Git reference to use for triggering the workflow"
    required: false
    default: main
  inputs:
    description: "JSON string of inputs to pass to the workflow"
    required: false
    default: |
      {}
  wait_interval:
    description: "Interval in seconds to wait between polling workflow status"
    required: false
    default: 10s
  timeout:
    description: "Maximum time to wait for the workflow to complete"
    required: false
    default: 1h
  action:
    description: "Action to perform: trigger-and-wait, trigger-only, wait-only"
    required: false
    default: trigger-and-wait
  run_id:
    description: "Run ID of the workflow to wait for (required for wait-only action)"
    required: false
    default: trigger-and-wait
  no_throw:
    description: |
      If set to 'yes' or 'true', will not throw errors when waiting for a workflow,
      instead will print the error message to 'run_conclusion' output.
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
