name: "Test Action"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build the action (if TypeScript is used)
      - name: Build Action
        run: npm run build

      # Run the action with a test workflow
      - name: Run Test Action
        id: run-test
        uses: ./ # Use the current action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          workflow_id: "test-workflow.yml"
          ref: "main"
          inputs: '{"key1": "value1", "key2": "value2"}'
          wait_interval: "10000"
          timeout: "60000"
          action: "trigger-and-wait"

      # Verify the output
      - name: Verify Outputs
        run: |
          echo "Run Conclusion: ${{ steps.run-test.outputs.run_conclusion }}"
