name: Test Workflow
run-name: Test Workflow (${{ inputs.RunPattern || 'no-pattern' }})

on:
  workflow_dispatch:
    inputs:
      Timeout:
        description: "Timeout for the action in minutes"
        required: true
        default: "5"
        type: string
      Throw:
        description: "Throw error"
        required: true
        default: "no"
        type: string
      RunPattern:
        description: "Run Pattern"
        required: false
        type: string
  workflow_call:
    inputs:
      Timeout:
        description: "Timeout for the action in minutes"
        required: true
        default: "5"
        type: string
      Throw:
        description: "Throw error"
        required: true
        default: "no"
        type: string
      RunPattern:
        description: "Run Pattern"
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Step
        run: |
          echo '{
            "Timeout": "${{ inputs.Timeout }}",
            "Throw": "${{ inputs.Throw }}",
            "RunPattern": "${{ inputs.RunPattern }}"
          }' | jq -r . | tee -a $GITHUB_STEP_SUMMARY
          echo "Test workflow started";
          echo "Sleeping ${{ inputs.Timeout }} seconds";
          sleep ${{ inputs.Timeout }};
          if [[ "${{ inputs.Throw }}" == "yes" ]]; then
          echo "Throwing error";
          exit 1;
          fi;
          echo "Test workflow ended";
